name: release

on:
  release:
    types: [published]

jobs:
  release-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: Gr1N/setup-poetry@v8
      - name: Install Poetry dependencies
        run: poetry install
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      - name: Create Python package
        run: poetry build
      - name: Publish package to PyPi
        run: poetry publish -u __token__ -p $token
        env:
          token: ${{ secrets.PYPI_API_TOKEN }}
  
